export interface ProductConfig {
  id: string;
  name: string;
  category: string;
  headline: string;
  description: string;
  themeGradient: string;
  image: string;
  highlights: string[];
  quickFacts: { label: string; value: string }[];
  minPremium: string;
  benefits: { icon: string; title: string; desc: string }[];
  covered: string[];
  notCovered: string[];
  faqs: { q: string; a: string }[];
  relatedProducts: string[];
}

export const PRODUCTS: Record<string, ProductConfig> = {
  'platinum-plus': {
    id: 'platinum-plus', name: 'Platinum Plus', category: 'Life Insurance',
    headline: 'Guaranteed Savings with Life Protection from Day One',
    description: 'A distinctive savings and protection scheme providing 10 years of insurance coverage with premiums waived for the first 3 years. Build wealth while protecting what matters most.',
    themeGradient: 'from-brand-950 via-brand-800 to-brand-700',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1400&q=80',
    highlights: ['Premiums Waived First 3 Years', 'Guaranteed Returns', '10-Year Coverage'],
    quickFacts: [{ label: 'Plan Duration', value: '10 Years' }, { label: 'Entry Age', value: '18 – 55 Years' }, { label: 'Sum Assured', value: 'PKR 500K – 10M' }, { label: 'Premium Waiver', value: 'First 3 Years' }],
    minPremium: '3,500',
    benefits: [
      { icon: 'Shield', title: 'Premium Waiver', desc: 'No premium payments required for the first 3 years of your policy — full coverage from day one.' },
      { icon: 'TrendingUp', title: 'Guaranteed Returns', desc: 'Your savings grow at a guaranteed rate, unaffected by market volatility.' },
      { icon: 'Heart', title: 'Life Cover', desc: 'Your family receives the full sum assured immediately upon your passing.' },
      { icon: 'DollarSign', title: 'Maturity Benefit', desc: 'Receive the full accumulated sum plus bonuses at policy maturity.' },
      { icon: 'RefreshCw', title: 'Loan Facility', desc: 'Borrow up to 90% of surrender value after 2 policy years.' },
      { icon: 'UserCheck', title: 'Disability Waiver', desc: 'Premiums waived in event of permanent total disability.' },
    ],
    covered: ['Death from any cause', 'Accidental death double benefit', 'Critical illness rider (optional)', 'Disability premium waiver', 'Maturity survival benefit', 'Bonus accumulation'],
    notCovered: ['Suicide within first 2 years', 'War or civil commotion', 'Self-inflicted injuries', 'Pre-existing conditions without disclosure'],
    faqs: [
      { q: 'What happens if I miss a premium payment?', a: 'A grace period of 30 days is allowed. After that, the policy enters a paid-up status where reduced benefits remain active.' },
      { q: 'Can I surrender the policy early?', a: 'Yes, after 2 full years a surrender value is payable. The value increases with each policy year.' },
      { q: 'Is the plan available for overseas Pakistanis?', a: 'Yes. Overseas Pakistanis can purchase Platinum Plus through our digital platform or authorized agents.' },
      { q: 'How is the guaranteed return calculated?', a: 'The guaranteed return is a fixed percentage of sum assured declared annually, independent of investment performance.' },
      { q: 'What documents are needed to apply?', a: 'Original CNIC, recent passport-size photo, income proof, and completed proposal form.' },
      { q: 'When does the premium waiver for 3 years apply?', a: 'From the policy commencement date for the first 36 months. State Life covers this cost — you pay nothing.' },
    ],
    relatedProducts: ['jeevan-saathi', 'digital-insurance', 'takaful'],
  },
  'jeevan-saathi': {
    id: 'jeevan-saathi', name: 'Jeevan Saathi', category: 'Life Insurance',
    headline: 'One Policy That Protects Both of You, Together',
    description: 'A joint life plan covering two partners — pays out on the death of either insured person. Build a future together, knowing both lives are protected under a single policy.',
    themeGradient: 'from-[#1a0a2e] via-[#3b1568] to-[#2d1456]',
    image: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=1400&q=80',
    highlights: ['Covers Both Partners', 'Single Premium Payment', 'Pays on First Death'],
    quickFacts: [{ label: 'Lives Covered', value: '2 (Joint)' }, { label: 'Entry Age', value: '18 – 60 Years' }, { label: 'Policy Term', value: '10 – 30 Years' }, { label: 'Payout Trigger', value: 'First Death' }],
    minPremium: '4,200',
    benefits: [
      { icon: 'Users', title: 'Dual Coverage', desc: 'Both partners protected under one plan — pays the full sum assured on the first death.' },
      { icon: 'Shield', title: 'Surviving Partner Benefit', desc: 'The surviving partner receives full payout plus all future premiums are waived.' },
      { icon: 'Clock', title: 'Flexible Terms', desc: 'Choose a policy term between 10 and 30 years to match your life stage.' },
      { icon: 'DollarSign', title: 'Maturity Benefit', desc: 'If both partners survive to maturity, the full sum assured plus bonuses is paid.' },
      { icon: 'RefreshCw', title: 'Loan Facility', desc: 'Access up to 90% of the surrender value during the policy term.' },
      { icon: 'Heart', title: 'Rider Options', desc: 'Add critical illness, accidental death, or disability riders for enhanced protection.' },
    ],
    covered: ['Death of either partner from any cause', 'Accidental death enhanced benefit', 'Critical illness (with rider)', 'Permanent disability waiver', 'Maturity survival benefit', 'Bonuses on sum assured'],
    notCovered: ['Death within 2 years from suicide', 'Undisclosed pre-existing conditions', 'War, invasion, or armed conflict', 'Criminal acts by insured'],
    faqs: [
      { q: 'Does the second partner remain covered after a claim?', a: 'No — once the sum assured is paid on the first death, the policy ends. The surviving partner receives the full benefit.' },
      { q: 'Can unmarried partners apply?', a: 'Jeevan Saathi is designed for spouses. Unmarried business partners may qualify — speak to an agent for eligibility.' },
      { q: 'What if both partners die simultaneously?', a: 'The sum assured is paid to the nominated beneficiary as a single lump sum.' },
      { q: 'Can we increase coverage after marriage?', a: 'A top-up facility is available at marriage anniversary milestones without fresh medical underwriting.' },
      { q: 'Is medical examination required?', a: 'For sum assured under PKR 2M, medical examination may be waived based on age and health declaration.' },
      { q: 'What happens to premiums if one partner becomes disabled?', a: 'With the disability rider, all future premiums are waived while full coverage continues.' },
    ],
    relatedProducts: ['platinum-plus', 'sehat-sahulat', 'digital-insurance'],
  },
  'sehat-zindagi': {
    id: 'sehat-zindagi', name: 'Sehat Zindagi', category: 'Health Insurance',
    headline: 'Complete Health Protection for You, Every Day',
    description: 'Comprehensive individual health insurance covering inpatient and outpatient treatment at 30,000+ panel hospitals nationwide. One card, total peace of mind.',
    themeGradient: 'from-[#002616] via-[#014d28] to-[#01843a]',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1400&q=80',
    highlights: ['30,000+ Panel Hospitals', 'Cashless Treatment', 'Inpatient & Outpatient'],
    quickFacts: [{ label: 'Coverage Type', value: 'Individual' }, { label: 'Entry Age', value: '18 – 64 Years' }, { label: 'Annual Limit', value: 'Up to PKR 1M' }, { label: 'Cashless Network', value: '30,000+ Hospitals' }],
    minPremium: '2,800',
    benefits: [
      { icon: 'Activity', title: 'Inpatient Coverage', desc: 'Full hospital admission costs covered including room, ICU, surgical fees and medicines.' },
      { icon: 'Stethoscope', title: 'Outpatient Cover', desc: 'GP consultations, specialist visits, diagnostics and pharmacy costs reimbursed.' },
      { icon: 'Zap', title: 'Emergency Care', desc: '24/7 emergency treatment covered at any empanelled hospital with no pre-authorization.' },
      { icon: 'Baby', title: 'Maternity Benefit', desc: 'Normal and caesarean delivery costs covered after 10-month waiting period.' },
      { icon: 'Eye', title: 'Dental & Optical', desc: 'Annual dental checkups and optical consultations included in comprehensive plans.' },
      { icon: 'Phone', title: 'Telemedicine', desc: 'Unlimited virtual doctor consultations included with all Sehat Zindagi plans.' },
    ],
    covered: ['Hospitalization for illness or injury', 'Pre & post hospitalization expenses', 'Day care procedures', 'Emergency ambulance', 'Cancer treatment', 'Maternity (after waiting period)'],
    notCovered: ['Cosmetic or aesthetic procedures', 'Dental treatment (basic plan)', 'Self-inflicted injuries', 'Substance abuse treatment', 'War and terrorism', 'Experimental treatments'],
    faqs: [
      { q: 'How do I use my Sehat Card at a hospital?', a: 'Present your Sehat Card at the hospital admission desk. The hospital verifies directly with State Life — no cash needed.' },
      { q: 'Can I use any hospital?', a: 'You must use empanelled hospitals for cashless treatment. For non-panel hospitals, reimbursement claims are available.' },
      { q: 'Is there a waiting period for pre-existing conditions?', a: 'Yes, a 1-year waiting period applies for pre-existing conditions declared at enrollment.' },
      { q: 'Does the plan cover my parents?', a: 'Sehat Zindagi covers the individual policyholder. For family coverage, consider Sehat Sahulat.' },
      { q: 'What is the claim reimbursement timeline?', a: 'Reimbursement claims are settled within 15 working days of receiving complete documentation.' },
      { q: 'Can I renew the plan annually?', a: 'Yes, annual renewal is available with no medical underwriting if the policy has been continuously active.' },
    ],
    relatedProducts: ['sehat-sahulat', 'platinum-plus', 'takaful'],
  },
  'sehat-sahulat': {
    id: 'sehat-sahulat', name: 'Sehat Sahulat', category: 'Health Insurance',
    headline: 'One Premium Covers Your Entire Family',
    description: 'Comprehensive group health insurance for the whole family under one affordable annual premium. Every member gets the same quality coverage — from newborns to parents.',
    themeGradient: 'from-[#002616] via-[#025930] to-[#014d28]',
    image: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=1400&q=80',
    highlights: ['Entire Family Covered', 'One Annual Premium', 'Newborn Coverage'],
    quickFacts: [{ label: 'Coverage Type', value: 'Family (up to 6)' }, { label: 'Entry Age', value: '0 – 64 Years' }, { label: 'Family Limit', value: 'PKR 2.5M/year' }, { label: 'Members Covered', value: 'Spouse + 4 Children' }],
    minPremium: '5,500',
    benefits: [
      { icon: 'Users', title: 'Full Family Cover', desc: 'Policyholder, spouse, and up to 4 dependent children on a single policy.' },
      { icon: 'Baby', title: 'Newborn Coverage', desc: 'Newborns covered from birth — add them to the policy within 30 days at no extra cost in year 1.' },
      { icon: 'Shield', title: 'No Sub-limits', desc: 'No per-person sub-limits — the full annual benefit is shared across all family members.' },
      { icon: 'Activity', title: 'Chronic Illness', desc: 'Ongoing treatment for chronic conditions covered after the standard waiting period.' },
      { icon: 'Globe', title: 'International Cover', desc: 'Emergency coverage valid in Gulf Cooperation Council countries for traveling families.' },
      { icon: 'Smartphone', title: 'Digital Health Card', desc: 'Each family member gets a digital Sehat Card accessible on the State Life Health Plus App.' },
    ],
    covered: ['All family members hospitalization', 'Maternity — normal and C-section', 'Pediatric specialist consultations', 'Cancer and dialysis treatment', 'ICU and high dependency care', 'Ambulance and emergency transport'],
    notCovered: ['Cosmetic surgery', 'Infertility treatments', 'Dental (basic plan)', 'Obesity treatment', 'Experimental drugs', 'Injuries from extreme sports'],
    faqs: [
      { q: 'Can I add my parents to Sehat Sahulat?', a: 'Parents are not included in the standard family definition. A separate individual Sehat Zindagi policy for parents is recommended.' },
      { q: 'What happens when children turn 25?', a: 'Dependent children are covered until age 25 (or marriage, whichever is earlier) before they need their own policy.' },
      { q: 'Is there a maternity waiting period?', a: 'Yes, a 10-month waiting period applies from policy inception for maternity benefits.' },
      { q: 'How many claims can I make per year?', a: 'Unlimited claims up to the total annual family benefit limit of PKR 2.5 million.' },
      { q: 'Can I upgrade the plan mid-year?', a: 'Plan upgrades are available at annual renewal. Mid-year upgrades are subject to underwriting review.' },
      { q: 'Does the plan cover dental for children?', a: 'Basic dental for children under 12 is included. Orthodontic treatment is available on the comprehensive plan.' },
    ],
    relatedProducts: ['sehat-zindagi', 'platinum-plus', 'corporate'],
  },
  'takaful': {
    id: 'takaful', name: 'Takaful Products', category: 'Islamic Insurance',
    headline: 'Protection Built on Mutual Cooperation and Islamic Values',
    description: 'Sharia-compliant insurance products following the principles of Tabarru (donation) and Mudarabah (profit-sharing). Certified by leading Islamic scholars — protection without compromise.',
    themeGradient: 'from-[#1a1200] via-[#3d2c00] to-[#5c4200]',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1400&q=80',
    highlights: ['Sharia Certified', 'No Riba (Interest)', 'Surplus Distributed to Members'],
    quickFacts: [{ label: 'Structure', value: 'Mudarabah Model' }, { label: 'Certification', value: 'Sharia Board Approved' }, { label: 'Surplus Sharing', value: 'Annual Distribution' }, { label: 'Entry Age', value: '18 – 60 Years' }],
    minPremium: '3,000',
    benefits: [
      { icon: 'Star', title: 'Sharia Compliant', desc: 'Certified by an independent Sharia Supervisory Board — no interest (riba), no uncertainty (gharar).' },
      { icon: 'Users', title: 'Mutual Cooperation', desc: 'Participants contribute to a shared fund (Tabarru). Surplus returned to members annually.' },
      { icon: 'TrendingUp', title: 'Halal Investment', desc: 'All contributions invested exclusively in Sharia-compliant instruments and sukuk.' },
      { icon: 'DollarSign', title: 'Surplus Distribution', desc: 'Annual surplus from the Takaful fund distributed back proportionally to participants.' },
      { icon: 'Shield', title: 'Full Life Cover', desc: 'Same comprehensive death and disability benefits as conventional products — Islamically structured.' },
      { icon: 'RefreshCw', title: 'Savings Component', desc: 'A portion of contributions grows in a participant investment account, accessible at maturity.' },
    ],
    covered: ['Death from any cause', 'Permanent total disability', 'Critical illness (with rider)', 'Maturity survival benefit', 'Accidental death enhancement', 'Disability premium waiver'],
    notCovered: ['Non-Halal business activities by policyholder', 'Suicide within 2 years', 'Undisclosed pre-existing conditions', 'War and terrorism', 'Criminal acts', 'Self-inflicted harm'],
    faqs: [
      { q: 'What makes Takaful different from conventional insurance?', a: 'Conventional insurance involves risk transfer (potentially involving riba). Takaful is based on mutual donation (Tabarru) and shared risk — participants help each other.' },
      { q: 'Who certifies the Sharia compliance?', a: 'An independent Sharia Supervisory Board composed of recognized Islamic scholars reviews and approves all products and investments annually.' },
      { q: 'What happens to investment surplus?', a: 'After deducting valid claims and expenses, the surplus of the Takaful fund is distributed to participants on a pro-rata basis.' },
      { q: 'Is there a Takaful health product?', a: 'Yes. Health Takaful provides the same coverage as Sehat Zindagi but is structured as a Takaful arrangement.' },
      { q: 'Can I convert my existing conventional policy to Takaful?', a: 'Yes, within certain guidelines. A formal request and re-underwriting process applies. Speak to a Takaful specialist agent.' },
      { q: 'Are Takaful profits guaranteed?', a: 'The Tabarru (donation) component is not returned, but the investment account grows based on Halal investment performance — not guaranteed but historically positive.' },
    ],
    relatedProducts: ['platinum-plus', 'sehat-zindagi', 'digital-insurance'],
  },
  'corporate': {
    id: 'corporate', name: 'Corporate Group Insurance', category: 'Corporate Solutions',
    headline: 'Protect Your Workforce — The Foundation of Your Business',
    description: 'Comprehensive group life, health, and savings plans designed for employers who value their people. Retain top talent, reduce absenteeism, and fulfill your duty of care.',
    themeGradient: 'from-brand-950 via-brand-800 to-[#0a3366]',
    image: 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1400&q=80',
    highlights: ['Group Life Cover', 'Employee Health Plans', 'Flexible Scheme Design'],
    quickFacts: [{ label: 'Minimum Group', value: '10 Employees' }, { label: 'Coverage Types', value: 'Life + Health + Savings' }, { label: 'Billing', value: 'Annual / Quarterly' }, { label: 'Admin Portal', value: 'HR Dashboard Access' }],
    minPremium: 'Custom Quote',
    benefits: [
      { icon: 'Briefcase', title: 'Group Life Cover', desc: 'Lump-sum death benefit for employee families — typically 3x annual salary.' },
      { icon: 'Activity', title: 'Group Health Plan', desc: 'Inpatient and outpatient coverage for all employees and eligible dependents.' },
      { icon: 'TrendingUp', title: 'Group Savings Scheme', desc: 'Employer and employee contribute to a managed savings fund — paid at retirement or resignation.' },
      { icon: 'Shield', title: 'Accidental Coverage', desc: 'Personal accident and disability coverage included at no additional premium.' },
      { icon: 'Monitor', title: 'HR Admin Portal', desc: 'Dedicated online portal for HR teams to add/remove members, download certificates, and file claims.' },
      { icon: 'BarChart2', title: 'Annual Utilization Report', desc: 'Detailed usage analytics per department to optimize your benefits spend every year.' },
    ],
    covered: ['Employee death from any cause', 'Hospitalization for all conditions', 'Outpatient treatment', 'Maternity for female employees', 'Permanent disability', 'Accidental injuries'],
    notCovered: ['Pre-existing conditions declared at enrollment (1-year wait)', 'Cosmetic procedures', 'Substance abuse', 'Injuries from illegal activities', 'War and civil unrest', 'Experimental treatments'],
    faqs: [
      { q: 'What is the minimum number of employees to qualify?', a: 'A minimum of 10 full-time employees is required. Below this threshold, individual plans are recommended.' },
      { q: 'Can we customize coverage levels by employee grade?', a: 'Yes. Coverage tiers can be structured by grade — senior management can receive enhanced benefits vs. general staff.' },
      { q: 'How are premium payments structured?', a: 'Annual payment with quarterly installment option. Group discount applies for groups over 100 employees.' },
      { q: 'How long does enrollment take?', a: 'From proposal acceptance to policy issuance typically takes 7–10 working days.' },
      { q: 'What if an employee leaves the company?', a: 'Coverage ends on termination date. The employee may convert to an individual policy within 30 days without fresh medical underwriting.' },
      { q: 'Is there an online portal for HR to manage claims?', a: 'Yes — the HR Admin Portal allows direct claim submission, status tracking, member management, and certificate download 24/7.' },
    ],
    relatedProducts: ['sehat-sahulat', 'platinum-plus', 'digital-insurance'],
  },
  'digital-insurance': {
    id: 'digital-insurance', name: 'Digital Insurance', category: 'Digital Products',
    headline: 'Full Insurance Coverage in Under 10 Minutes — No Agent Needed',
    description: "Pakistan's first fully digital insurance purchase experience. Get covered instantly from your phone — no paperwork, no medical exam under PKR 2M, no waiting.",
    themeGradient: 'from-[#060d1f] via-[#0d1f4d] to-[#0f2566]',
    image: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1400&q=80',
    highlights: ['100% Online', 'Instant Policy Issuance', 'No Paperwork'],
    quickFacts: [{ label: 'Purchase Time', value: 'Under 10 Minutes' }, { label: 'Medical Exam', value: 'Not Required < 2M' }, { label: 'Policy Delivery', value: 'Instant (Email/SMS)' }, { label: 'Payment', value: 'JazzCash / EasyPaisa' }],
    minPremium: '1,200',
    benefits: [
      { icon: 'Smartphone', title: 'Buy Instantly Online', desc: 'Complete purchase in under 10 minutes from any device — mobile, tablet, or desktop.' },
      { icon: 'Zap', title: 'Instant Policy Issuance', desc: 'Policy document delivered to your email and SMS immediately upon payment confirmation.' },
      { icon: 'FileText', title: 'Zero Paperwork', desc: 'Entirely paperless — CNIC verification is digital. No physical forms or signatures.' },
      { icon: 'CreditCard', title: 'Multiple Payment Methods', desc: 'Pay via JazzCash, EasyPaisa, bank debit card, or credit card instantly.' },
      { icon: 'RefreshCw', title: 'Auto-Renewal', desc: 'Annual auto-renewal with SMS confirmation — never let your coverage lapse accidentally.' },
      { icon: 'Headphones', title: '24/7 Digital Support', desc: 'WhatsApp support and in-app chat available around the clock for claims and queries.' },
    ],
    covered: ['Death from any cause', 'Accidental death double benefit', 'Permanent total disability', 'Critical illness (optional add-on)', 'Hospitalization cash benefit', 'Nominee payment within 48 hours'],
    notCovered: ['Sum assured over PKR 2M requires medical exam', 'Pre-existing conditions undisclosed', 'Suicide within first 2 years', 'Death from war or terrorism', 'Hazardous activities', 'Criminal acts'],
    faqs: [
      { q: 'Is a digital policy legally valid?', a: 'Yes. Digital policies issued by State Life carry the same legal validity as paper policies under SECP regulations.' },
      { q: 'How do I file a claim on a digital policy?', a: 'Submit claim documents via the State Life app or WhatsApp. A claims officer contacts you within 24 hours.' },
      { q: 'Can I increase my coverage later?', a: 'Yes, coverage can be increased at annual renewal. Increases above PKR 2M will require medical underwriting.' },
      { q: 'What CNIC verification is required?', a: 'Your CNIC number is verified against NADRA records digitally during the purchase process.' },
      { q: 'What if I lose my policy document?', a: 'Log in to the State Life app or website to re-download your policy document anytime.' },
      { q: 'Can overseas Pakistanis buy digitally?', a: 'Yes. NICOP holders can purchase digital insurance from anywhere in the world using an international payment card.' },
    ],
    relatedProducts: ['platinum-plus', 'takaful', 'jeevan-saathi'],
  },
  'alpha-insurance': {
    id: 'alpha-insurance', name: 'Alpha Insurance', category: 'Subsidiary Products',
    headline: 'Specialized Protection Under the State Life Umbrella',
    description: "Alpha Life Insurance — a wholly-owned subsidiary of State Life incorporated in 1991 — offering specialized protection products with the backing of Pakistan's largest insurer.",
    themeGradient: 'from-ink-950 via-ink-800 to-ink-700',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1400&q=80',
    highlights: ['State Life Subsidiary', 'Since 1991', 'Specialized Plans'],
    quickFacts: [{ label: 'Established', value: '1991' }, { label: 'Parent Company', value: 'State Life' }, { label: 'Regulated By', value: 'SECP' }, { label: 'Plan Types', value: 'Individual & Group' }],
    minPremium: '2,500',
    benefits: [
      { icon: 'Award', title: 'Backed by State Life', desc: "Full financial backing of State Life — Pakistan's most creditworthy insurer with AAA PACRA rating." },
      { icon: 'Shield', title: 'Specialized Products', desc: 'Alpha offers niche products tailored to market segments not covered by standard State Life plans.' },
      { icon: 'TrendingUp', title: 'Competitive Premiums', desc: 'Efficient subsidiary structure allows more competitive pricing on select product lines.' },
      { icon: 'Globe', title: 'Gulf & Overseas Products', desc: 'Specialized plans for Pakistani workers in Gulf countries and other overseas markets.' },
      { icon: 'FileText', title: 'Straightforward Terms', desc: 'Clear, simple policy documents designed for policyholders who prefer straightforward coverage terms.' },
      { icon: 'Headphones', title: 'Dedicated Support', desc: 'Dedicated Alpha customer service team with direct escalation to State Life management.' },
    ],
    covered: ['Death from any cause', 'Accidental death benefit', 'Disability coverage', 'Savings maturity benefit', 'Loan facility after 2 years', 'Overseas emergency coverage'],
    notCovered: ['Pre-existing undisclosed conditions', 'Suicide within 2 years', 'War and terrorism', 'Criminal activities', 'Hazardous sports', 'Self-inflicted harm'],
    faqs: [
      { q: 'How is Alpha different from State Life main products?', a: "Alpha focuses on specialized segments and niche markets. It operates with more flexibility in product design while maintaining State Life's financial strength." },
      { q: 'Are Alpha policies covered by the same guarantees?', a: "Yes. As a wholly-owned subsidiary, Alpha policies benefit from State Life's financial strength and regulatory compliance." },
      { q: 'Can I transfer an Alpha policy to a State Life policy?', a: 'Conversion options are available at certain policy milestones. Consult an authorized agent for details.' },
      { q: 'Is Alpha available in all provinces?', a: "Alpha operates through State Life's nationwide network of agents and offices across all provinces." },
      { q: 'What specialized products does Alpha offer?', a: 'Alpha specializes in Gulf worker protection, group credit life, mortgage protection, and customized corporate solutions.' },
      { q: 'How do I contact Alpha customer service?', a: 'Alpha is accessible through all State Life offices and the central helpline 0800-700-900.' },
    ],
    relatedProducts: ['platinum-plus', 'corporate', 'digital-insurance'],
  },
};
