import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['Sora', 'sans-serif'],
        body: ['DM Sans', 'sans-serif'],
        urdu: ['Noto Nastaliq Urdu', 'serif'],
      },
      fontSize: {
        'display-2xl': ['clamp(3rem,6vw,5rem)', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-xl': ['clamp(2.25rem,4vw,3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '700' }],
        'display-lg': ['clamp(1.75rem,3vw,2.5rem)', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['clamp(1.375rem,2.5vw,1.875rem)', { lineHeight: '1.2', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-xl': ['1.25rem', { lineHeight: '1.7' }],
        'body-lg': ['1.125rem', { lineHeight: '1.7' }],
        'body-md': ['1rem', { lineHeight: '1.7' }],
        'body-sm': ['0.875rem', { lineHeight: '1.6' }],
        'body-xs': ['0.75rem', { lineHeight: '1.6' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          600: '#006400',
          500: '#01843A',
          400: '#00A650',
          300: '#33C27A',
          200: '#80DBA8',
          100: '#CCF2E1',
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        brand: {
          950: '#020B18',
          900: '#041425',
          800: '#062040',
          700: '#0A3366',
          600: '#0F4C99',
          500: '#1560BD',
          400: '#3A7FD4',
          300: '#6FA8E8',
          200: '#A8CCF0',
          100: '#D6E8FA',
          50: '#EDF5FD',
        },
        gold: {
          600: '#92600A',
          500: '#B8860B',
          400: '#D4A017',
          300: '#F0C040',
          200: '#F8DC8A',
          100: '#FDF3D0',
        },
        ink: {
          950: '#0A0A0F',
          900: '#111118',
          800: '#1C1C28',
          700: '#2D2D3F',
          600: '#454560',
          500: '#6B6B8A',
          400: '#9494AA',
          300: '#BBBBD0',
          200: '#DCDCE8',
          100: '#F0F0F6',
          50: '#F8F8FC',
        },
        success: '#00A650',
        warning: '#F59E0B',
        error: '#DC2626',
        info: '#1560BD',
      },
      boxShadow: {
        'card': '0 1px 3px rgba(10,10,15,0.06), 0 4px 16px rgba(10,10,15,0.08)',
        'card-hover': '0 8px 32px rgba(21,96,189,0.15), 0 2px 8px rgba(10,10,15,0.06)',
        'modal': '0 24px 80px rgba(10,10,15,0.25)',
        'nav': '0 2px 20px rgba(10,10,15,0.08)',
        'glow-blue': '0 0 40px rgba(21,96,189,0.3)',
        'glow-green': '0 0 40px rgba(0,166,80,0.25)',
        'inset-top': 'inset 0 1px 0 rgba(255,255,255,0.1)',
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        fadeUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideLeft: { '0%': { opacity: '0', transform: 'translateX(24px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        pulseGlow: { '0%,100%': { boxShadow: '0 0 20px rgba(21,96,189,0.2)' }, '50%': { boxShadow: '0 0 50px rgba(21,96,189,0.5)' } },
        float: { '0%,100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-12px)' } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        'fade-up': 'fadeUp 0.6s ease forwards',
        'fade-in': 'fadeIn 0.4s ease forwards',
        'slide-left': 'slideLeft 0.5s ease forwards',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
